config/routes.rb
Assessor::Application.routes.draw do
  root :to => 'home#index'

  get "home/index"
  get "developers" => "home#developers"
  get "about" => "home#about"
  get "contact" => "home#contact"

  get "score/index"

  get "course" => "course#index"

  get "profile/display" => "profile#display"
  get "profile/edit" => "profile#edit"
  post "profile/edit" => "profile#update"
  get "profile/consent" => "profile#consent"
  post "profile/record_consent" => "profile#record_consent"
  get "exercises/progress" => "exercises#progress"
  resources :exercises
  resources :handouts
  resources :videos

  match '/api/v1/user/exercises/:exercise/problems/:problem/attempt' => 'score#attempt',
    :constraints => { :problem => /\d+/ }, :via => :post

  match '/api/v1/user/exercises/:exercise/problems/:problem/hint' => 'score#hint',
    :constraints => { :problem => /\d+/ }, :via => :post

  get "explorations" => "explorations#index"
  get "explorations/derivative" => "explorations#derivative"
  get "explorations/traffic" => "explorations#traffic"
  get "explorations/graph" => "explorations#graph"
  get "explorations/trigExplore" => "explorations#trigExplore"
  get "explorations/doppler" => "explorations#doppler"
  get "explorations/trains" => "explorations#trains"
  get "explorations/fifths" => "explorations#fifths"
end

app/models/handout.rb
class Handout < ActiveRecord::Base
  attr_accessible :order, :title, :url, :week
end

app/controllers/handouts_controller.rb
class HandoutsController < ApplicationController
  # GET /handouts
  # GET /handouts.json
  def index
    @handouts = Handout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handouts }
    end
  end

  # GET /handouts/1
  # GET /handouts/1.json
  def show
    @handout = Handout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handout }
    end
  end

  # GET /handouts/new
  # GET /handouts/new.json
  def new
    @handout = Handout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @handout }
    end
  end

  # GET /handouts/1/edit
  def edit
    @handout = Handout.find(params[:id])
  end

  # POST /handouts
  # POST /handouts.json
  def create
    @handout = Handout.new(params[:handout])

    respond_to do |format|
      if @handout.save
        format.html { redirect_to @handout, notice: 'Handout was successfully created.' }
        format.json { render json: @handout, status: :created, location: @handout }
      else
        format.html { render action: "new" }
        format.json { render json: @handout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /handouts/1
  # PUT /handouts/1.json
  def update
    @handout = Handout.find(params[:id])

    respond_to do |format|
      if @handout.update_attributes(params[:handout])
        format.html { redirect_to @handout, notice: 'Handout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @handout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handouts/1
  # DELETE /handouts/1.json
  def destroy
    @handout = Handout.find(params[:id])
    @handout.destroy

    respond_to do |format|
      format.html { redirect_to handouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/handouts_helper.rb
module HandoutsHelper
end

app/views/handouts/_form.html.erb
<%= form_for(@handout) do |f| %>
  <% if @handout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handout.errors.count, "error") %> prohibited this handout from being saved:</h2>

      <ul>
      <% @handout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :week %><br />
    <%= f.number_field :week %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handouts/edit.html.erb
<h1>Editing handout</h1>

<%= render 'form' %>

<%= link_to 'Show', @handout %> |
<%= link_to 'Back', handouts_path %>

app/views/handouts/index.html.erb
      <div class="row">
        <div class="span1"></div>
        <div class="span6">
          <div class="hero-unit">
            <h1>the <%=raw html_logo %> textbook</h1>
	    <p>Reading a math textbook is not quite the same as reading a novel&mdash;math is even more fun!  To read mathematics, you need to bring a bit more than just the textbook to the table: you should also bring
<ul>
<li>a pen,</li>
<li>plenty of blank paper, and</li>
<li>courage to write everything down.</li>
</ul>
<p>As you read mathematics, you must work along side of the text
itself. You must <strong>write</strong> down each
expression, <strong>sketch</strong> each graph,
and <strong>think</strong>&mdash;always think!&mdash;about just what
you are doing. You should work examples and fill in the details.  Like
all great things, this is no easy task.</p>
<p>You can begin reading now by <a href="/textbook/mooculus.pdf">downloading the textbook</a>.</p>
          </div>
        </div>
        <div class="span5">
	  <div id="myCarousel" class="carousel slide">
	    <!-- Carousel items -->
	    <div class="carousel-inner">
	      <div class="item"><a href="/textbook/mooculus.pdf"><img src="/images/textbook-1.png" class="img-rounded"/></a>
		<div class="carousel-caption"> 
                  <h4>Free and open</h4> 
                  <p>Unlike most calculus textbooks, this book won't cost you a thing.</p> 
                </div>
	      </div>
	      <div class="active item"><a href="/textbook/mooculus.pdf"><img src="/images/textbook-2.png" class="img-rounded"/></a>
		<div class="carousel-caption"> 
                  <h4>Week 10</h4> 
                  <p>Only the beginning of the book has been written, but this version includes new material for Week 9 on linear approximation.</p>
                </div>
	      </div>
	      <div class="item"><a href="/textbook/mooculus.pdf"><img src="/images/textbook-3.png" class="img-rounded"/></a>
		<div class="carousel-caption"> 
                  <h4>Extra material</h4> 
                  <p>The textbook goes into more details than the lectures, and includes more practice problems.</p>
                </div>
	      </div>
	    </div>
	    <!-- Carousel nav -->
	    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
	  </div>

	  <p>

	  </p>
	    <a href="/textbook/mooculus.pdf" class="btn btn-large btn-block btn-primary" type="button"><i class="icon-download-alt"></i> Download the Textbook</a>

	    <a href="/textbook/mooculus-print.pdf" class="btn btn-block btn-info" type="button"><i class="icon-print"></i> Get the printable version with a white background</a>

	</div>
      </div>

app/views/handouts/new.html.erb
<h1>New handout</h1>

<%= render 'form' %>

<%= link_to 'Back', handouts_path %>

app/views/handouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @handout.title %>
</p>

<p>
  <b>Url:</b>
  <%= @handout.url %>
</p>

<p>
  <b>Order:</b>
  <%= @handout.order %>
</p>

<p>
  <b>Week:</b>
  <%= @handout.week %>
</p>


<%= link_to 'Edit', edit_handout_path(@handout) %> |
<%= link_to 'Back', handouts_path %>