config/routes.rb
Assessor::Application.routes.draw do
  root :to => 'home#index'

  get "home/index"
  get "developers" => "home#developers"
  get "about" => "home#about"
  get "contact" => "home#contact"

  get "score/index"

  get "course" => "course#index"

  get "profile/display" => "profile#display"
  get "profile/edit" => "profile#edit"
  post "profile/edit" => "profile#update"
  get "profile/consent" => "profile#consent"
  post "profile/record_consent" => "profile#record_consent"
  get "exercises/progress" => "exercises#progress"
  resources :exercises
  resources :handouts
  resources :videos

  match '/api/v1/user/exercises/:exercise/problems/:problem/attempt' => 'score#attempt',
    :constraints => { :problem => /\d+/ }, :via => :post

  match '/api/v1/user/exercises/:exercise/problems/:problem/hint' => 'score#hint',
    :constraints => { :problem => /\d+/ }, :via => :post

  get "explorations" => "explorations#index"
  get "explorations/derivative" => "explorations#derivative"
  get "explorations/traffic" => "explorations#traffic"
  get "explorations/graph" => "explorations#graph"
  get "explorations/trigExplore" => "explorations#trigExplore"
  get "explorations/doppler" => "explorations#doppler"
  get "explorations/trains" => "explorations#trains"
  get "explorations/fifths" => "explorations#fifths"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @exercises = Exercise.order(:position)
    @competencies = current_user.competencies if user_signed_in?
    @exercises_by_weeks = (Exercise.order(:position).group_by &:week)
  end

  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, :notice => 'Exercise was successfully created.' }
        format.json { render :json => @exercise, :status => :created, :location => @exercise }
      else
        format.html { render :action => "new" }
        format.json { render :json => @exercise.errors, :status => :unprocessable_entity }
      end
    end
  end

  def new
    @exercise = Exercise.new
  end

  def edit
  end

  def show
    if /[a-z]/i =~ params[:id]
      page = "#{params[:id]}.html".downcase
      @exercise = Exercise.find(:first, 
                                :conditions => ["lower(page) = ?", page])
    else
      @exercise = Exercise.find(params[:id])
    end
    @problem = @exercise.problem_from_bag

    conditions = {
      :user_id => current_user.id,
      :exercise_id => @exercise.id }
    
    @competency = Competency.where(conditions).limit(1).first
  end

  def update
  end

  def destroy
  end

  def progress
    unless user_signed_in?
      redirect_to user_omniauth_authorize_path(:coursera)
      return 
    end

    exercises = Exercise.order(:position)
    completed_exercises = 
      current_user.competencies.order(:estimate).reverse_order.map { |c| c.exercise }
    incomplete_exercises = exercises - completed_exercises
    @exercises = completed_exercises + incomplete_exercises
    @competencies = Competency
    @exercises_by_weeks = (completed_exercises.group_by &:week)
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
  def progress_on(exercise)
    competency = @competencies.find_by_exercise_id(exercise.id)
    progress = (competency.max_estimate * 100).round
    modifier = case progress
               when 0..50 then " bar-danger"
               when 51..80 then " bar-warning"
               else " bar-success"
               end

    %(<div class="bar#{modifier}" style="width: #{progress}%;"></div>)
  end
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_area :page %>
  </div>
  <div class="field">
    <%= f.label :problem_number %><br />
    <%= f.text_area :problem_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/_index_exercise.html.erb
<tr>
  <td>
    <%= link_to exercise.title, exercise %>
  </td>
  <% if user_signed_in? %>
    <td>
      <% if @competencies.where(exercise_id: exercise.id).first %>
        <div class="progress" style="margin-bottom: 0px;">
          <%= raw progress_on(exercise) %>
        </div>
      <% else %>
        <div class="progress" style="margin-bottom: 0px;">
          <div class="bar" style="width: 0%;"></div>
        </div>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/exercises/_progress_exercise.html.erb
<tr>
  <td>
    <%= link_to exercise.title, exercise %>
  </td>
  <% if user_signed_in? %>
    <td>
      <% if @competencies.where(exercise_id: exercise.id).first %>
        <div class="progress" style="margin-bottom: 0px;">
          <%= raw progress_on(exercise) %>
        </div>
      <% else %>
        <div class="progress" style="margin-bottom: 0px;">
          <div class="bar" style="width: 0%;"></div>
        </div>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/exercises/index.html.erb
<% if current_user %>
<p>To learn mathematics, you must practice.  Even if you aren't entirely sure you will succeed, <strong>jump in!</strong>  Click on an exercise, and if you don't know what to do, ask for a <strong>hint</strong>.</p>
<% else %>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Login!</strong>  To do the practice exercises, you must first <%= link_to 'sign in to Coursera', user_omniauth_authorize_path(:coursera) %>.
</div>
<% end %>

<% current_week = 15 %>

<div class="accordion" id="accordion">
<% for week in @exercises_by_weeks.keys.sort.reverse %>
<% if week <= current_week %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= week %>">
        <h4>Week <%= week %></h4>
      </a>
    </div>
    <div id="collapse<%= week %>" class="accordion-body collapse <% if week == current_week %> in <% end %>">
      <div class="accordion-inner">

<table class="table table-striped">
  <thead>
   <tr>
    <th>
      Problem
    </th> 
    <% if user_signed_in? %>
      <th>
        Progress
      </th>
    <% end %>
   </tr>
  </thead>

  <tbody>
    <% @exercises_by_weeks[week].each do |exercise| %>
      <%= render partial: "index_exercise", locals: { exercise: exercise } %>
    <% end %>
  </tbody>
</table>

        
      </div>
    </div>
  </div>
<% end %>
<% end %>
</div>

app/views/exercises/khan_exercise.html.erb
<!--
    TODO: eventually, this template can replace khan-exercises/exercises/khan-exercise.html,
    which is used in exercise test mode
-->

<div id="exercise-message-container" style="display: none;">
    <div class="exercise_message"></div>
</div>
<div id="warning-bar">
    <span id="warning-bar-content"></span>
    <span id="warning-bar-close">(<a href="">close</a>)</span>
</div>
<div id="problem-and-answer">
    <div id='problemarea'>
        <div id='scratchpad'><div></div></div>
        <div id='workarea'></div>
        <div id='hintsarea'></div>
    </div>
    <div id="answer_area_wrap"><div id="answer_area">
        <form id="answerform" action="/exercisedashboard" method="get" name="answerform">
            <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px">
            <div id="answercontent" class="info-box">
                <span id="examples-show">Acceptable formats</span>
                <span class="info-box-header">Answer</span>
                <div id="solutionarea" class="fancy-scrollbar"></div>
                <ul id="examples" style="display: none"></ul>
                <div class="answer-buttons">
                <input type="button" class="simple-button green" id="check-answer-button" value="Check Answer"/>
                <input type="button" class="simple-button green" id="next-question-button" style="display:none;" name="correctnextbutton" value="Correct! Next Question..."/>
                <div id="positive-reinforcement"><img src="/images/face-smiley.gif" /></div>
                <span id="show-solution-button-container"></span>
                <div id="check-answer-results"><p class="check-answer-message info-box-sub-description"></p></div>
                </div>
            </div>
            <div id="readonly" class="info-box">
                <span id="readonly-problem" class="info-box-header"></span>
                <span id="readonly-title" class="info-box-subheader">You are viewing a problem.</span>
                <span class="info-box-sub-description">To work on problems like this, <a id="readonly-start" href="">start this exercise</a>.</span>
            </div>
            <div class="info-box hint-box">
                <span class="info-box-header">Need help?</span>
                <div id="get-hint-button-container">
                    <input id="hint" type="button" class="simple-button orange full-width" value="I'd like a hint" name="hint"/>
                </div>
                <span id="hint-remainder"></span>
            </div>
            <div class="info-box related-video-box" style="display:none;">
                <div id="related-video-content">
                    <span class="info-box-header">Stuck? Watch a video.</span>

                    <div id="related-video-list">
                        <span class="related-content-title">Related videos:</span>
                        <ul class="related-video-list"></ul>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </form>
        <div id="calculator" class="info-box" style="display: none;">
            <span class="info-box-header">Calculator</span>
            <div class="calculator">
                <div class="history fancy-scrollbar">
                    <div class="calc-row input"><input type="text"><div class="status"><a href="#" data-behavior="angle-mode"><br>DEG</a></div></div>
                </div>
                <div class="keypad">
                    <div class="calc-row">
                    <a href="#" data-text="asin(">sin<sup>-1</sup></a><a href="#" data-text="acos(">cos<sup>-1</sup></a><a href="#" data-text="atan(">tan<sup>-1</sup></a><a href="#" data-behavior="bs">del</a><a href="#" data-behavior="clear" class="dark">ac</a>
                    </div>
                    <div class="calc-row">
                    <a href="#" data-text="sin(">sin</a><a href="#" data-text="cos(">cos</a><a href="#" data-text="tan(">tan</a><a href="#" data-text="sqrt(">&radic;</a><a href="#" data-text="^">x<sup>y</sup></a>
                    </div>
                    <div class="calc-row">
                    <a href="#" class="dark">7</a><a href="#" class="dark">8</a><a href="#" class="dark">9</a><a href="#">(</a><a href="#">)</a>
                    </div>
                    <div class="calc-row">
                    <a href="#" class="dark">4</a><a href="#" class="dark">5</a><a href="#" class="dark">6</a><a href="#" data-text="*">&times;</a><a href="#" data-text="/">&divide;</a>
                    </div>
                    <div class="calc-row">
                    <a href="#" class="dark">1</a><a href="#" class="dark">2</a><a href="#" class="dark">3</a><a href="#">+</a><a href="#" data-text="-">&minus;</a>
                    </div>
                    <div class="calc-row">
                    <a href="#" class="dark">0</a><a href="#" class="dark">.</a><a href="#" data-text="ans">ans</a><a href="#" data-behavior="evaluate" class="wide">=</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="issue" class="info-box" style="display:none;">
            <span class="info-box-header">Report a Problem</span>
            <span id="issue-status" class="info-box-sub-description"></span>
            <form>
                <fieldset>
                    <legend>Issue Type</legend>
                    <ul>
                        <li>
                            <input type="radio" name="issue-type" id="issue-wrong-or-unclear">
                            <label for="issue-wrong-or-unclear">Answer is wrong or question is unclear</label>
                        </li>
                        <li>
                            <input type="radio" name="issue-type" id="issue-hard">
                            <label for="issue-hard">I'm frustrated (tell us why) or this is too hard</label>
                        </li>
                        <li>
                            <input type="radio" name="issue-type" id="issue-not-showing">
                            <label for="issue-not-showing">I can't see the problem or website is stuck</label>
                        </li>
                        <li>
                            <input type="radio" name="issue-type" id="issue-other">
                            <label for="issue-other">Other (please describe below)</label>
                        </li>
                    </ul>
                </fieldset>
                <label for="issue-title">Issue Title:<input type="text" name="issue-title" id="issue-title" /></label>
                <label for="issue-email">Your Email (optional):<input type="text" name="issue-email" id="issue-email" /></label>
                <label for="issue-body">Description of Issue:<textarea name="issue-body" id="issue-body"></textarea></label>
                <input type="submit" class="simple-button" value="Submit Issue">
                <a href="/#" id="issue-cancel">Cancel</a>
                <img id="issue-throbber" style="display:none;" name="issue-throbber">
            </form>
        </div>
    </div></div>
    <div style="clear: both;"></div>
</div>

app/views/exercises/khan_site.html.erb
        <div id="outer-wrapper">
            <div id="page-container">
                <div id="page-container-inner">
                    <div id="fb-root"></div>
                    <header>
                        <div id="top-header">
                            <div class="top-header-links">
                                <span class="page_links" id="page_auth">
                                    <span class="achievement-badge-counts" style="left:-60px;"></span>
                                    <span><a href="http://mooculus.osu.edu/login">Log in</a></span>
                                    <span class="separator"></span>
                                    <span><a href="http://mooculus.osu.edu/contribute" id="donate-link">Donate</a></span>
                                </span>
                                <div class="clear"></div>
                                <div id="nav-and-search">
                                    <div class="sitewide-navigation">
                                        <nav>
                                            <span class="links nav-subheader">
                                                <span class="dropdown topic-browser-dropdown">
                                                    <a href="http://mooculus.osu.edu/#browse" class="watch-link dropdown-toggle">Watch <span class="caret"></span></a>
                                                <a href="http://mooculus.osu.edu/exercisedashboard" class="selected practice-link">Practice</a>
                                                <a href="http://mooculus.osu.edu/class_profile">Coach</a>
                                                <a href="http://mooculus.osu.edu/contribute">Volunteer</a>
                                                <a href="http://mooculus.osu.edu/about">About</a>
                                                </span>
                                            </span>
                                        </nav>
                                    </div>
                                    <div id="search-box">
                                        <form class="page-search" action="/search">
                                            <input id="search-input" type="text" placeholder="Search for a video or topic" name="page_search_query" value="" class="ui-corner-all placeholder simple-input search-input blur-on-esc ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true"><input type="submit" value=" " id="search-submit" class="search-submit" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true"/>
                                        </form>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>

                            <div id="logo">
                                <a id="logo-image" href="http://mooculus.osu.edu/" title="Khan Academy" name="logo-image"></a>
                                <div id="stats"><span id="page_visitors" style="display: inline;">Over 9,000 lessons delivered</span></div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </header>
                    <div id="container" class="single-exercise visited-no-recolor" style="overflow: hidden;">
                        <article class="exercises-content clearfix">
                        <div class="exercises-header"><h2 class="section-headline">
                                <div class="topic-exercise-badge">&nbsp;</div>
                                <span class="practice-exercise-topic-context">Practicing</span>
                        </h2></div>
                        <div class="exercises-body">
                            <div class="exercises-stack">&nbsp;</div>
                            <div class="exercises-card current-card">
                                <div class="current-card-container card-type-problem">
                                    <div class="current-card-container-inner vertical-shadow">
                                        <div class="current-card-contents">
                                        </div>
                                    </div>
                                    <div id="extras" class="single-exercise">
                                        <ul>
                                            <li> <a id="scratchpad-show" href style>Show scratchpad</a>
                                                <span id="scratchpad-not-available" style="display: none;">Scratchpad not available</span>
                                            </li>
                                            <li class="debug-mode"> <a href="?debug">Debug mode</a></li>
                                            <li> <a id="problem-permalink" href>Problem permalink</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </article>
                    </div>
                    <div id="end-of-page-spacer" style="height: 38px;">&nbsp;</div>
                    <div id="badge-notification-container" class="badge-award-container" style="display:none;"></div>
                </div>
            </div>
        </div>

        <div class="push"></div>
        <footer id="footer" class="short">
            <div id="leaves">
                <div class="inner">
                    <div id="copyright" class="tiny">
                        <small>&copy;2012 Khan Academy&#0153;</small> <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" id="creative-commons-link" name="creative-commons-link"></a>
                    </div>
                    <span class="footer-links">
                        <a href="http://mooculus.osu.edu/">FAQ</a>
                        <span class="sep">|</span>
                        <a href="/reportissue?type=Defect&issue_labels=Component-Code%2CExercise-addition_1%2CProblem-1" id="report">Report a Problem</a>
                        <span class="sep">|</span>
                        <a href="/about/the-team">Contact</a><a href="/jobs">Jobs</a>
                        <span class="sep">|</span>
                        <a href="/about/tos" title="Terms of Service">ToS</a> <a href="/about/privacy-policy" title="Privacy Policy">Privacy Policy</a>
                        <span class="sep">|</span>
                        <a href="/downloads">Downloads</a>

                        <span class="sep">|</span>
                        <span class="small-social-links">
                        </span>
                    </span>
                </div>
            </div>
        </footer>

app/views/exercises/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/progress.html.erb
<h3>Exercises</h3>

<div class="accordion" id="accordion">
<% for week in @exercises_by_weeks.keys.sort %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= week %>">
        <h4>Week <%= week %></h4>
      </a>
    </div>
    <div id="collapse<%= week %>" class="accordion-body collapse">
      <div class="accordion-inner">

<table class="table table-striped">
  <thead>
   <tr>
    <th>
      Problem
    </th> 
    <% if user_signed_in? %>
      <th>
        Progress
      </th>
    <% end %>
   </tr>
  </thead>

  <tbody>
    <% @exercises_by_weeks[week].each do |exercise| %>
      <%= render partial: "progress_exercise", locals: { exercise: exercise } %>
    <% end %>
  </tbody>
</table>

        
      </div>
    </div>
  </div>
<% end %>
</div>

<h3>Your Badges</h3>

<ul>
<% for badge in current_user.badges %>
<li><span class="badge badge-success"><%= badge.name %></span> <%= badge.description %></li>
<% end %>
</ul>

<h3>Achievements</h3>

<ul>
<li>You have spent
<% if current_user.total_thinking_time > 5*60 %>
  <% if current_user.total_thinking_time > 3*60*60 %>
    <%= current_user.total_thinking_time / (60*60) %> hours
  <% else %>
    <%= current_user.total_thinking_time / 60 %> minutes
  <% end %>
<% else %>
 <%= current_user.total_thinking_time %> seconds
<% end %>
 working problems.</li>
<li>You have submitted <%= current_user.total_correct_answers %> correct answers.</li>
</ul>